/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonNavItem: typeof import('./src/components/common/commonNavItem/index.vue')['default']
    CommonNavItemDetil: typeof import('./src/components/common/commonNavItemDetil/index.vue')['default']
    DemoSearch: typeof import('./src/components/common/demoSearch/index.vue')['default']
    EjectCard: typeof import('./src/components/common/ejectCard/index.vue')['default']
    ExpansionBar: typeof import('./src/components/common/expansionBar/index.vue')['default']
    NCarousel: typeof import('naive-ui')['NCarousel']
    RotationChart: typeof import('./src/components/common/rotationChart/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/common/search/index.vue')['default']
  }
}
